version: '3'

services:
  web:
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: lab2
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3305:3306"