"""create mytable

Revision ID: 4fefabe5cc31
Revises: b11e4577d164
Create Date: 2023-04-18 16:38:06.886950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fefabe5cc31'
down_revision = 'b11e4577d164'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
