"""create mytable

Revision ID: 9a4d910c668b
Revises: 4fefabe5cc31
Create Date: 2023-04-18 16:39:40.009813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4d910c668b'
down_revision = '4fefabe5cc31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
