"""create mytable

Revision ID: b034f69e33a6
Revises: c449a7fef31c
Create Date: 2023-04-18 16:31:27.787870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b034f69e33a6'
down_revision = 'c449a7fef31c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
