"""create mytable

Revision ID: b11e4577d164
Revises: b034f69e33a6
Create Date: 2023-04-18 16:33:55.872303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11e4577d164'
down_revision = 'b034f69e33a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
