"""create mytable

Revision ID: c29e7a440d09
Revises: 9a4d910c668b
Create Date: 2023-04-18 16:57:26.998970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29e7a440d09'
down_revision = '9a4d910c668b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
